from geral.config import *
from modelo.professor import *
from modelo.aluno import *
from modelo.pessoa import *
from modelo.autor import *
from modelo.musica import *
from modelo.turma import *
from modelo.instrumento import *
from modelo.agenda import *
